---
sudo: required
sudo: true
dist: trusty

language: minimal

services:
  - docker

before_install:
  - echo "DockerHub credentials"
  - echo "$DOCKER_PASSWORD" | sudo docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "DockerHub credentials - [ OK ] "
  - sudo docker build -t getninjas/spot-ninja .

after_success:
  - echo "branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then echo -e "Push Container"; fi
  - echo "$DOCKER_PASSWORD" | sudo docker login -u "$DOCKER_USERNAME" --password-stdin
  - export REPO=getninjas/spot-ninja
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - sudo docker build -f Dockerfile -t $REPO:$TAG .
  - sudo docker push $REPO
